#!/usr/bin/env bash
IDENTITY_FILE="$HOME/.ssh/id_rsa"
USERNAME="$1"
WEB_IP="$2"

if [ "$#" -ne 2 ]; then
	echo "usage: $0 USERNAME WEB_IP"
	exit 1
fi

scp -i "$IDENTITY_FILE" /mnt/c/Users/user/Desktop/alx-system_engineering-devops/0x0C-web_server/4-not_found_page_404 "$USERNAME@$WEB_IP:~/"

# ssh into web-02 and run the script

ssh -i "$IDENTITY_FILE" -t "$USERNAME@$WEB_IP" <<EOF 
chmod +x 4-not_found_page_404
./4-not_found_page_404
EOF
