#!/usr/bin/env bash
# install's, configures and restarts the server 
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx Http'
echo "hello world" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

sudo tee /etc/nginx/sites-available/default > /dev/null << EOL
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.nginx-debian.html

	server_name pageforge.tech;

	location / {
		try_files $uri $uri/ = 404;
	}

	location /redirect_me{
		return 301 htttps://www.example.com;
	}

	# custome 404 error page configuration
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}

}
EOL

# Restart Nginx to apply the changes
sudo service nginx reload