#!/usr/bin/env bash
# creating and managing a load balancer
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.2
sudo apt-get update
sudo apt-get install haproxy=2.2.\*

#Enable haproxy
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# listen to web01 and web02 servers
echo "frontend http_front
    	bind *:80
    	stats uri /haproxy?stats
    	default_backend http_back

	backend http_back
    	balance roundrobin
    	server web01 55308-web-01:80 check
    	server web02 55308-web-02:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
