#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
sudo sed -i 's/listen 80 default_server;/listen 80;/; s/listen \[::\]:80 default_server;/listen [::]:80;/g' /etc/nginxsites-available/default
service nginx start
sudo systemctl stop nginx 
