#!/usr/bin/env bash
# Configures Nginx to listen on port 80 and stops the service
sudo sed -i 's/listen 80 default_server;/listen 80;/; s/listen \[::\]:80 default_server;/listen [::]:80;/g' /etc/nginx/sites-available/default
sudo ufw allow 'Nginx Full'
sudo systemctl stop nginx

